common:
  app:
    name: tsunagaru
    page_description: 1ボタンで簡単にメッセージ！ 家族や友人など、あなたの大切な人へ想いを届けよう。
    page_keywords: "つながる,ツナガル,繋がる,メッセージ,めっせーじ,チャット,ちゃっと,ボタン,療養"
    page_title: 1ボタンで想いを届けよう
    og:
      title: 1ボタンで簡単にメッセージ！ 家族や友人など、あなたの大切な人へ想いを届けよう。
      type: website
      url: https://tsunagaru.space
      image: site_image.jpg
      site_name: tsunagaru
      description: 1ボタンで簡単にメッセージ！ 家族や友人など、あなたの大切な人へ想いを届けよう。
    mail:
      from: '"tsunagaru" <noreply@tsunagaru.space>'
    contact: https://twitter.com/Artefacttw
  password:
    minimum_count: 6
  domain: tsunagaru.space

twitter:
  url: https://twitter.com
  account_name: Artefacttw
  share_url: https://twitter.com/intent/tweet
  card: summary_large_image
  auto_fill_password_count: 8
  hashtag: tsunagaru-chat

user:
  avatar:
    default_file_name: avatar_sample.png
    by_sns_file_name: profile_image
    default_size_class: myavatar-m

room:
  limit_of_entry: 15
  alert_orientation_file_name: alert_orientation.png

setting:
  message_button:
    default_count: 6

env:
  can_login: CAN_LOGIN
  can_create_user: CAN_CREATE_USER
  aws_s3_bucket_name: AWS_S3_BUCKET_NAME
  aws_access_key_id: AWS_ACCESS_KEY_ID
  aws_secret_access_key: AWS_SECRET_ACCESS_KEY
  aws_region: AWS_REGION
